from __future__ import annotations

from typing import Protocol

from brain.progress.models import IngestionJob


class ProgressStore(Protocol):
    def create_job(self, *, project: str, workspace_id: str) -> IngestionJob: ...

    def update_job(self, job_id: str, **fields) -> None: ...

    def complete_job(self, job_id: str, *, active_index: str) -> None: ...

    def fail_job(self, job_id: str, *, error: str) -> None: ...

    def get_job(self, job_id: str) -> IngestionJob | None: ...

    def list_jobs(self, *, workspace_id: str, limit: int = 10) -> list[IngestionJob]: ...
